package Main;

import com.demo.Product;
import logic.CrudOPProduct;

public class MainClassProduct {
	public static void main(String args[]) {
		
		//id automaticllay generated by hibernte engine
		
		CrudOPProduct serve = new CrudOPProduct();
		Product newproducts = new Product();
		
		newproducts.setColor("GOLD");
		newproducts.setLaptopName("APPLE ");
		newproducts.setModel("DONT CARE");
		newproducts.setsize("24 inches");
		newproducts.setWeight("2000 tons");
		
		serve.addProduct(newproducts);
		
		
		/*Product updateProduct = new Product();
	    updateProduct.setColor("BLACK");
		updateProduct.setLaptopName("HP & DELL ");
		updateProduct.setModel("i dont know");
		updateProduct.setsize("20 inches");
		updateProduct.setWeight("100 tons");*/
		//list of products
	
	
	
		//getall method is this...................
		//serve.getdetailsall();
	
	
	
	
	/*	List<Product> listofprod = (List) serve.getProductDetails(details , 16);
		System.out.println(listofprod);
		serve.getdetailsall();
		Product product = serve.getdetails(16);
		System.out.println(	
		"product name is "+product.getLaptopName()+"product colour is "+product.getColor()+
		"product size is "+product.getsize()+"product model is "+	product.getModel()+
		"product weight is "+product.getWeight());*/
		
	 
		
		//DELETE ALL ..................................
		//System.out.print(serve.deletall());
		
		
		
		// UPDATE .......................................
		/*
		 
		 Product updated =  new Product();
				
		updated.setLaptopName("microsoft");		
		updated.setsize("45");
		updated.setWeight("5grams");
		updated.setColor("red");
		serve.updateEmployeById(updated, 16);
		System.out.println("Now the LaptopName is: " + updated.getLaptopName());
		
		System.out.println("Operation successful!!");  */
	
		// DELETE BY ID ..................................
	//	serve.deletedetailsByID(17);
	
	}

}